### ISSUE TITLE
query points on point clouds 

### ISSUE THREAD

**Issue by srasoulzadeh** [ErlerPhilipp/points2surf#13]
Dear Philip,

Thanks for providing the code for this super interesting paper.
I have read all of the paper and still, one question has remained for me: When using pre-trained models for just inference (mesh reconstruction) out of point clouds, how the query points are defined from the point clouds?

In the paper, it is mentioned that query points are defined by randomly sampling 1000 points on the surface and offset them in the normal direction. However, in the case of using just point clouds for the reconstruction once the model is trained, there would be no surface to sample query points from them, I wonder how these are defined in this case.

Thank you in advance.

**Comment by ErlerPhilipp** [comment]
Hi @srasoulzadeh,

> In the paper, it is mentioned that query points are defined by randomly sampling 1000 points on the surface and offset them in the normal direction. However, in the case of using just point clouds for the reconstruction once the model is trained, there would be no surface to sample query points from them, I wonder how these are defined in this case.

You're right, there is no surface to sample for inference. I don't remember exactly where this is in the paper but it must belong to the training set generation.

For inference, we take all voxels that are within epsilon distance from any point of the point cloud as query points. For "eval_p2s_max.sh" e.g., this parameter is set to 3. This means that areas in scan shadows are ignored and filled it (likely with errors) by the sign propagation. Also, noisy point clouds may require many more network evaluations than noise-free point clouds.

Does this answer your question?

**Comment by srasoulzadeh** [comment]
Thank you very much for the quick response.

Of course, now I got the point that how are they defined.

By the way, I am experimenting with some point clouds obtained through sketching in a 3D environment.
In some cases, it works perfectly fine (SAMPLE WALL Num. 1) while in some another it drastically fails (SAMPLE WALL Num. 2). Might it be because of the fact that sketches produce very noisy point clouds? and due to that, might it require some more parameter modifications?

Attached, I provided the screenshots from Blender visualizing the input point cloud and respective reconstructed mesh as output. 

##### SAMPLE WALL 1 IMAGES
[SAMPLE WALL #1 POINT CLOUD](https://user-images.githubusercontent.com/23161701/129538493-eed30aef-53a0-4c2d-8515-32f67b5563fa.png)
[SAMPLE WALL #1 RECONSTRUCTED MESH](https://user-images.githubusercontent.com/23161701/129538667-eb208efe-2289-4aa8-96cb-a0618f1031d6.png)

##### SAMPLE WALL 2 IMAGES
[SAMPLE WALL #2 POINT CLOUD](https://user-images.githubusercontent.com/23161701/129538824-49997a30-a664-409a-8c9c-ee5db43ed441.png)
[SAMPLE WALL #2 RECONSTRUCTED MESH](https://user-images.githubusercontent.com/23161701/129539013-a27a2d93-893c-41ff-85a5-ca60ee45393c.png)

**Comment by ErlerPhilipp** [comment]
Yes, you the holes in the scans may produce some errors. But the main problem with your examples is that they don't have a thickness (as far as I can see). The underlying geometry representation of P2S is an SDF, which enforces solid objects. P2S is also trained on solid (mostly single) objects. To get more reasonable results, you would need to to "simulate" a solid object. I don't know if this is applicable in your case. Maybe, you could extrude the sketches somehow to get at least a front and back side?

**Comment by srasoulzadeh** [comment]
You are right, this is exactly the case.
For instance, the SAMPLE WALL Num. 1 has a small amount of thickness and the output is perfectly acceptable, but in SAMPLE WALL Num. 2 it has no thickness, and also in my other examples that there exist no thickness the algorithm fails.
This was a very important notice. I try the extrusion and see what the results would be.

Thank you very much @ErlerPhilipp for your responses.
