### ISSUE TITLE
ABC training set

### ISSUE THREAD

**Issue by raphaelsulzer** [ErlerPhilipp/points2surf#14]
Hi,

Thank you for making this great work available here.

Would it be possible to share your training data, the (scanned) 5k shapes from the ABC dataset?

Kind regards

**Comment by raphaelsulzer** [comment]
I just noticed that there is a "download_datasets_abc_training.py" file. It wasn't listed in the docs like the rest, so I didn't think it was there.

**Comment by ErlerPhilipp** [comment]
in case anyone else needs the dataset, you can download it directly from our [publication database](https://www.cg.tuwien.ac.at/research/publications/2020/erler-2020-p2s/erler-2020-p2s-abc_training.zip)
