### ISSUE TITLE
How to get query points while reconstructing

### ISSUE THREAD

**Issue by QtEngineer** [ErlerPhilipp/points2surf#16]
Hi,
I noticed the number of query point while constructing is highly more than 2000,about 50000.Does it equals to total amount of points from input npz file?

**Comment by ErlerPhilipp** [comment]
Hi @QtEngineer,

to be absolutely clear, there is a big difference between the number of query points while training and while reconstructing an object. During training, it's just some arbitrary constant (I think 10k). During reconstruction, it depends on the number of voxels near any point of the input point cloud. For more details, see the section about sign propagation in the paper and the code around line 304 of data_loader.py:
https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/source/data_loader.py#L304

**Comment by QtEngineer** [comment]
Thanks a lot ！
