### ISSUE TITLE
Error while running the max model evalution

### ISSUE THREAD

**Issue by Komti13** [ErlerPhilipp/points2surf#17]
running this command
bash experiments/eval_p2s_max.sh
 i keep getting this errror
  torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

any help please

**Comment by ErlerPhilipp** [comment]
Hi @Komti13,
the reason for this can be anything. You need to give more information about your setup. Most importantly, do you actually have a GPU with CUDA support? Drivers correctly installed? Can you run nvidia-smi?

**Comment by ErlerPhilipp** [comment]
closing for now, please reopen if necessary
