### ISSUE TITLE
didn’t get a  good reconstrcution result by directly using sdf.implicit_surface_to_mesh_directory

### ISSUE THREAD

**Issue by QtEngineer** [ErlerPhilipp/points2surf#18]
Hi,
    for testing ,I tried to reconstruct objs from abc_train datasets .I only used fuction sdf.implicit_surface_to_mesh_directory with argument 
query_dist_dir='abc_train\05_query_dist', 
query_pts_dir='abc_train\05_query_pts',
query_grid_resolution=128
sigma=5
certainty_threshold=13.
I opened gernerated ply&off file with meshlab , found all of them have many holes ,which quite different from GTmesh . 
Are there any problems when I run the  code?

**Comment by ErlerPhilipp** [comment]
Which model did you use? Which dataset? Even the full (vanilla) model has some problems with certain objects, i.e. open objects and landscapes. Also, the heuristic and sub-sampling is sensitive to varying point cloud density. Here is an unfortunate example from the Iso-Points paper:
![grafik](https://user-images.githubusercontent.com/7949665/168482326-5588b449-89e0-4d09-a11d-8143606833d5.png)

**Comment by QtEngineer** [comment]
I didnot use any model，only use   05_query_dist and 05_query_pts  from ABC_train datasets . 
Below is the result of 00010006_7e4956ae07e24f6584127385_trimesh_000.ply (generated  by  function sdf.implicit_surface_to_mesh_directory)
![image](https://user-images.githubusercontent.com/67670648/168526070-ed4d7e1b-716b-4a1a-8d20-f88197e147a9.png)
![微信截图_20220516134316](https://user-images.githubusercontent.com/67670648/168526783-088e0541-cbe0-4fd5-928b-6007b6581950.png)

**Comment by ErlerPhilipp** [comment]
Ahh I see. 05_query_dist and 05_query_pts contain only sparsely / randomly sampled training data. It's not a proper representation of the entire shapes and won't produce a good reconstruction. 

The GT shapes (03_meshes) should be included in the test sets for download. If you want the original input meshes, you would need to search the [ABC dataset](https://archive.nyu.edu/handle/2451/43778). To make things easier, I just uploaded the 03_meshes here: [https://www.cg.tuwien.ac.at/research/publications/2020/erler-2020-p2s/erler-2020-p2s-abc_meshes.zip](https://www.cg.tuwien.ac.at/research/publications/2020/erler-2020-p2s/erler-2020-p2s-abc_meshes.zip)

**Comment by QtEngineer** [comment]
Thanks a lot!
