### ISSUE TITLE
Cannot get correct surface representation by using Marchin_Cube

### ISSUE THREAD

**Issue by QtEngineer** [ErlerPhilipp/points2surf#19]
Hi,
I tried to save query_pts and query_dist of my own network after training,and then used fuction sdf.implicit_surface_to_mesh_directory from point2surf to reconstruct shapes but found that the generated mesh has a lot of vertics and faces (like this pic)
I checked  query_dist file and found  the dists are highly smaller than ABC_train datasets.  The average query_dist of mine is  0.00165,while ABC_train dataset is -0.08.  I don't know whether too small query_dist will cause reconstructing failed.
How can I fix it？
![20220518013127](https://user-images.githubusercontent.com/67670648/168874955-3d5db559-ff39-4c4a-a43d-8af82b96d69c.png)

**Comment by ErlerPhilipp** [comment]
Are you using the provided code for reconstruction? For example eval_p2s_vanilla.sh which calls full_eval.py. You can adapt these bash script to use your own model. If you use it correctly, you should get all the outputs in the results directory.

Even if the absolute distances are completely wrong, the main source of error is the occupancy. A large number of vertices and faces is normal for marching cubes. There is no mesh decimation applied in my code.

**Comment by QtEngineer** [comment]
Thanks a lot ！
