### ISSUE TITLE
 scikit-image>=0.22 in requirements: the latest is 0.18

### ISSUE THREAD

**Issue by DSLituiev** [ErlerPhilipp/points2surf#2]
The latest release is 0.18, but requirements says:
scikit-image>=0.22

https://github.com/scikit-image/scikit-image

**Comment by ErlerPhilipp** [comment]
I assume, you mean the requirements.txt. That's a copy-paste error from the p2s.yml. Please use Anaconda, the requirements.txt for Pip is just a fallback solution. Anyway, I only use basic features of scikit-image that should be available in pretty old releases.
