### ISSUE TITLE
dataset-from-point-clouds-for-reconstruction

### ISSUE THREAD

**Issue by Hxinyue** [ErlerPhilipp/points2surf#27]
Hello, what does the "00_base_pc" of "./datasets/(DATASET_NAME)/00_base_pc/" in this path mean?
I look forward to your reply.

**Comment by ErlerPhilipp** [comment]
That's where you put point cloud files ('.off', '.ply', '.obj', '.stl') that you want to reconstruct. Create a new folder in datasets with a name of your choice.
You need to change [line 168 in make_pc_dataset.py](https://github.com/ErlerPhilipp/points2surf/blob/master/make_pc_dataset.py#L168) to your _DATASET_NAME_. You may also want to change the setting _target_num_points_ to disable the subsampling. Keep in mind that P2S will perform poorly on large point clouds.
Then, run make_pc_dataset.py. 
After that, you need to modify an evaluation script in experiments to point to your new point cloud dataset and run it. Which one depends on the model you use. You'll find the reconstructions in the matching result folder.

**Comment by ErlerPhilipp** [comment]
please re-open if you have other issues
