### ISSUE TITLE
error in make_dataset.py: datasets/abc/00_base_meshes

### ISSUE THREAD

**Issue by DSLituiev** [ErlerPhilipp/points2surf#3]
I have downloaded the `abc` dataset using a `python datasets/download_datasets_abc.py` and I do see a folder in the `datasets/abc` with four files:

```
03_meshes
04_pts
settings.ini
testset.txt

```

When running `make_dataset.py` I am getting:

```
Traceback (most recent call last):
  File "make_dataset.py", line 813, in <module>
    make_dataset(dataset_name=d, blensor_bin=blensor_bin, base_dir=base_dir, num_processes=num_processes)
  File "make_dataset.py", line 724, in make_dataset
    clean_up_broken_inputs(base_dir=base_dir, dataset_dir=dataset_dir,
  File "make_dataset.py", line 534, in clean_up_broken_inputs
    final_output_files = [f for f in os.listdir(final_out_dir_abs)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/abc/00_base_meshes'

```

**Comment by ErlerPhilipp** [comment]
@DSLituiev The download scripts are meant for simple reproduction of the results, not exactly for reproducing the datasets. Also, I shouldn't just copy parts of the ABC dataset and redistribute them. If you want to reproduce the same dataset as in the paper, you can just copy-paste the (converted) mesh files from 03_meshes to 00_base_meshes. To make your own dataset, put other meshes in 00_base_meshes and make_dataset.py should be able to handle it.
