### ISSUE TITLE
How can I get colored reconstruction fron own point clouds?

### ISSUE THREAD

**Issue by rootpine** [ErlerPhilipp/points2surf#33]
Thanks for your excellent works!
I have own colored point-clouds data, and I would like to reconstruct mesh from it with color.
Currently, it looks like train_p2s_max.sh just outputs gray mesh.
Should I need modify make_pc_dataset.py or some other code ...?

**Comment by ErlerPhilipp** [comment]
Hi @rootpine !
Coloring is unfortunately not implemented here. You would need to implement it on your own.

For this, I see these options:
1. Vertex Colors: Quite easy but inefficient or ugly. Use a [Scipy KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html) and do a 1-NN query to copy the color to a mesh vertex from the closest point in your point cloud.
2. Texturing: Not so easy but quite nice. You could try [Xatlas ](https://github.com/jpcy/xatlas), [Blender](https://www.blender.org/), [Meshlab](https://www.meshlab.net/) or another texturing method. If this is in the context of photogrammetry (i.e. you have camera poses), you should have a look at [NerfStudio](https://github.com/nerfstudio-project/nerfstudio) and [OpenMVG](https://github.com/openMVG/openMVG). I'm also trying to figure this out, so I can't help you yet.

The best place to implement those is in source/sdf.py in implicit_surface_to_mesh(). You'll need to load the input point cloud here, so maybe pass the path through.

**Comment by ErlerPhilipp** [comment]
please re-open if you need more help
