### ISSUE TITLE
Reconstruct the raw point cloud

### ISSUE THREAD

**Issue by Zhong0501** [ErlerPhilipp/points2surf#36]
"Hello, can I directly use your model to reconstruct my point clouds? I noticed that your point cloud datasets are generated from meshes, but my point clouds are obtained through laser scanning." @ErlerPhilipp

**Comment by ErlerPhilipp** [comment]
Please see this and the following section in the readme: https://github.com/ErlerPhilipp/points2surf?tab=readme-ov-file#dataset-from-point-clouds-for-reconstruction
Let me know if you need more information.
