### ISSUE TITLE
training

### ISSUE THREAD

**Issue by zoswl** [ErlerPhilipp/points2surf#7]
Hi, @ErlerPhilipp !
I want to build my own point clouds dataset, I wonder if I can train with point clouds ？

**Comment by ErlerPhilipp** [comment]
Hi @zoswl 

The point of Points2Surf is to train with point clouds. I'm not sure I understand your issue. 
Please check the section "Make your own Datasets" in the readme. Is anything unclear there?

Do you mean, train without GT meshes? Then, no. You need the GT meshes to get the GT SDF.

**Comment by zoswl** [comment]
Thanks for your explanation！
Yep，I mean， train without GT meshes，I just didn't make it very clear.And now，I've got it.
Thanks again!

**Comment by ErlerPhilipp** [comment]
@zoswl 
one idea: if you don't have the GT meshes, you can perhaps simulate them, e.g. with Screened Poisson Surface Reconstruction. not sure how good it would work but it will give you some results.
