### ISSUE TITLE
Dataset variant naming

### ISSUE THREAD

**Issue by trisct** [ErlerPhilipp/points2surf#8]
Hi, thanks for releasing the code and the dataset!

In the paper you mentioned you created a dataset with medium noise (with the suffix ‘med’ to indicate this variant). But the downloaded datasets have no such variant. I wonder if it is no suffix for ABC, and ‘original’ for Famous and Thingi10k?

**Comment by ErlerPhilipp** [comment]
You are right, the dataset names are not exactly the same as in the paper. If I remember correctly (I don't have the datasets on my PC right now), ‘original’ for Famous and Thingi10k should be right. No suffix for ABC is probably what you mean with 'med', but it's actually varying noise strength.

Does this answer your question?

**Comment by trisct** [comment]
I am still a bit confused. In the paper, `med-noise` variants are defined to be the point clouds sampled with noise strength 0.01L. Do you mean the following?

- Famous-original (downloaded) = Famous-med-noise (in paper)
- Thingi10k-original (downloaded) = Thingi10k-med-noise (in paper)
- ABC (downloaded, no suffix) = ABC-var-noise (in paper)

**Comment by trisct** [comment]
Thanks for your reply!
