### ISSUE TITLE
Own dataset with point clouds as numpy arrays

### ISSUE THREAD

**Issue by kirbiyik** [ErlerPhilipp/points2surf#9]
I've already .npy files and they are normalized. I want to train this vanilla network on them. Is it enough if I put them into `04_pts` folder with the desired format. Or will I need to prepare `05_query_pts` as well? If so how can I prepare query points? Is there a useful script for that?

**Comment by ErlerPhilipp** [comment]
Hi @kirbiyik 

Please see Issue #7  (https://github.com/ErlerPhilipp/points2surf/issues/7). You need a 'GT' mesh to generate the training data. You can perhaps fake a GT mesh with another method like Poisson Reconstruction.

Does this answer your question?
